version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: smarthelpdesk-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: smarthelpdesk-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/smarthelpdesk
      - JWT_SECRET=supersecret
      - PORT=5000
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: smarthelpdesk-client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server

volumes:
  mongo_data: