services:
  - type: web
    name: smarthelpdesk-server
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://<your_mongo_atlas_uri>
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000